version: '1.0.{build}'

image: Visual Studio 2022

platform:
  - x64

configuration:
  - Release

before_build:
  - cd %APPVEYOR_BUILD_FOLDER%
  - mkdir build
  - cd build
  - cmake .. -G "Visual Studio 17 2022" -D CMAKE_PREFIX_PATH="C:\Qt\6.5.3\msvc2019_64" -D PYTHON_DIR="C:\Python39-x64"

build:
  project: $(APPVEYOR_BUILD_FOLDER)\build\$(APPVEYOR_PROJECT_NAME).sln